# Generated by Django 5.0.6 on 2025-08-13 03:57

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='steprun',
            name='sample',
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-created_at'], 'verbose_name': '项目', 'verbose_name_plural': '项目'},
        ),
        migrations.AddField(
            model_name='project',
            name='notes',
            field=models.TextField(blank=True, verbose_name='备注'),
        ),
        migrations.AddField(
            model_name='project',
            name='tags',
            field=models.JSONField(blank=True, default=list, verbose_name='标签'),
        ),
        migrations.AddField(
            model_name='steprun',
            name='order_index',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True, verbose_name='项目描述'),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=255, verbose_name='项目名称'),
        ),
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('dataset_type', models.CharField(choices=[('single_cell', 'Single Cell'), ('bulk_rna', 'Bulk RNA'), ('spatial', 'Spatial'), ('multiome', 'Multiome')], default='single_cell', max_length=20)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('input_h5ad_path', models.CharField(blank=True, max_length=500, null=True)),
                ('input_mtx_path', models.CharField(blank=True, max_length=500, null=True)),
                ('input_features_path', models.CharField(blank=True, max_length=500, null=True)),
                ('input_barcodes_path', models.CharField(blank=True, max_length=500, null=True)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datasets', to='projects.project')),
            ],
            options={
                'verbose_name': '数据集',
                'verbose_name_plural': '数据集',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('RUNNING', 'Running'), ('PAUSED', 'Paused'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='RUNNING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('last_active_at', models.DateTimeField(blank=True, null=True)),
                ('current_step', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='projects.step')),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='projects.dataset')),
                ('parent_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_sessions', to='projects.session')),
            ],
            options={
                'verbose_name': '会话',
                'verbose_name_plural': '会话',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='steprun',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='step_runs', to='projects.session'),
        ),
        migrations.DeleteModel(
            name='Sample',
        ),
    ]
