version: '3.9'
services:
  web:
    build:
      context: .
      dockerfile: docker/web.Dockerfile
    env_file:
      - .env
    command: ["sh", "-c", "python manage.py migrate && uvicorn bioai_platform.asgi:application --host 0.0.0.0 --port 8000"]
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
      - minio
      - worker
    volumes:
      - .:/app

  worker:
    build:
      context: .
      dockerfile: docker/worker.Dockerfile
    env_file:
      - .env
    command: ["celery", "-A", "bioai_platform", "worker", "-l", "INFO"]
    depends_on:
      - db
      - redis
      - minio
    volumes:
      - .:/app

  db:
    image: postgres:16
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  minio:
    image: minio/minio:RELEASE.2024-05-10T01-41-38Z
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ACCESS_KEY}
      MINIO_ROOT_PASSWORD: ${MINIO_SECRET_KEY}
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data

volumes:
  pgdata:
  minio_data: